# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Applicants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='nickname',
            field=models.CharField(default='unknown', max_length=50, verbose_name='nickname'),
        ),
    ]
